{
 "title": "Pose Estimation",
 "description": "Raw Metrics for Pose Estimation",
 "tags": [ "pose-estimation" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Shoulders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Left Shoulder",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "data_left_shoulder_value{data_left_shoulder_value=\"data_x_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_left_shoulder_value{data_left_shoulder_value=\"data_y_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_left_shoulder_value{data_left_shoulder_value=\"data_z_value\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Right Shoulder",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "data_right_shoulder_value{data_right_shoulder_value=\"data_x_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_right_shoulder_value{data_right_shoulder_value=\"data_y_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_right_shoulder_value{data_right_shoulder_value=\"data_z_value\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Elbows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Left Elbow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "data_left_elbow_value{data_left_elbow_value=\"data_x_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_left_elbow_value{data_left_elbow_value=\"data_y_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_left_elbow_value{data_left_elbow_value=\"data_z_value\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Right Elbow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "data_right_elbow_value{data_right_elbow_value=\"data_x_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_right_elbow_value{data_right_elbow_value=\"data_y_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_right_elbow_value{data_right_elbow_value=\"data_z_value\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Wrists", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Left Wrist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "data_left_wrist_value{data_left_wrist_value=\"data_x_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_left_wrist_value{data_left_wrist_value=\"data_y_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_left_wrist_value{data_left_wrist_value=\"data_z_value\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Right Wrist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "data_right_wrist_value{data_right_wrist_value=\"data_x_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_right_wrist_value{data_right_wrist_value=\"data_y_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_right_wrist_value{data_right_wrist_value=\"data_z_value\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hips", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Left Hip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "data_left_hip_value{data_left_hip_value=\"data_x_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_left_hip_value{data_left_hip_value=\"data_y_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_left_hip_value{data_left_hip_value=\"data_z_value\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Right Hip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "data_right_hip_value{data_right_hip_value=\"data_x_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_right_hip_value{data_right_hip_value=\"data_y_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_right_hip_value{data_right_hip_value=\"data_z_value\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Knees", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Left Knee",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "data_left_knee_value{data_left_knee_value=\"data_x_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_left_knee_value{data_left_knee_value=\"data_y_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_left_knee_value{data_left_knee_value=\"data_z_value\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Right Knee",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "data_right_knee_value{data_right_knee_value=\"data_x_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_right_knee_value{data_right_knee_value=\"data_y_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_right_knee_value{data_right_knee_value=\"data_z_value\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Feet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Left Foot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "data_left_foot_index_value{data_left_foot_index_value=\"data_x_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_left_foot_index_value{data_left_foot_index_value=\"data_y_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_left_foot_index_value{data_left_foot_index_value=\"data_z_value\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Right Foot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "data_right_foot_index_value{data_right_foot_index_value=\"data_x_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_right_foot_index_value{data_right_foot_index_value=\"data_y_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_right_foot_index_value{data_right_foot_index_value=\"data_z_value\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}