services:
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    ports:
      - "8080:8080"
    volumes: 
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices: 
      - "/dev/kmsg"
    networks:
      - localprom
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=24h'
      - '--web.enable-lifecycle'
    networks:
      - localprom
    ports:
      - 9090:9090
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    networks:
      - localprom
    ports:
      - 9100:9100
  alert-manager:
    image: prom/alertmanager
    container_name: alert-manager
    volumes:
      - "./alertmanager:/etc/alertmanager/"
    networks:
      - localprom
    ports:
      - 9093:9093
  pushgateway:
    image: prom/pushgateway:v1.1.0
    container_name: pushgateway
    networks:
      - localprom
    ports:
      - 9091:9091
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana
    networks:
      - localprom
    ports:
      - 3000:3000
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
      GF_PATHS_CONFIG: /etc/grafana/config.ini
  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: renderer
    networks:
      - localprom
    ports:
      - 8081:8081
networks:
  localprom:
    driver: bridge