global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alert-manager:9093
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: node
    static_configs:
      - targets:
        - node-exporter:9100
  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: 
        - pushgateway:9091
  - job_name: cadvisor
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - cadvisor:8080