apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    isDefault: true
    orgId: 1
    version: 1
    url: http://prometheus:9090
    user: ''
    database: ''
    basicAuth: false
    jsonData:
      httpMethod: POST
    readOnly: false